services: 
  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: lowcalories
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2.0'        # Máximo 2 CPU
          memory: 2G         # Máximo 2GB de RAM
        reservations:
          cpus: '0.5'        # Mínimo 0.5 CPU reservado
          memory: 1G         # Mínimo 1GB reservado

volumes:
  mysql_data:
    driver: local